from datetime import datetime, timezone, timedelta

MOCK_JOBS = [
    {
        "title": "Senior Frontend Engineer",
        "company": "Stripe",
        "location": "San Francisco, CA",
        "description": "Build and maintain Stripe's payment UI components. Work with React, TypeScript, and modern web technologies to create seamless checkout experiences used by millions.",
        "requirements": ["React", "TypeScript", "CSS-in-JS", "Testing"],
        "salary_min": 150000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "apply_url": "https://stripe.com/jobs",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "5000+",
    },
    {
        "title": "Backend Engineer — Go",
        "company": "Cloudflare",
        "location": "Austin, TX",
        "description": "Design and implement distributed systems that power Cloudflare's edge network. Work on performance, reliability, and scalability challenges at global scale.",
        "requirements": ["Go", "Distributed Systems", "PostgreSQL", "gRPC"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://cloudflare.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "3000+",
    },
    {
        "title": "Full Stack Developer",
        "company": "Notion",
        "location": "New York, NY",
        "description": "Help build the next generation of collaborative workspace tools. Work across the stack — from React frontends to scalable backend services.",
        "requirements": ["React", "Node.js", "PostgreSQL", "TypeScript", "REST APIs"],
        "salary_min": 130000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://notion.so/careers",
        "job_type": "Hybrid",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "500+",
    },
    {
        "title": "iOS Engineer",
        "company": "Spotify",
        "location": "Remote",
        "description": "Build features for Spotify's iOS app used by hundreds of millions of users. Focus on audio playback, discovery, and social features.",
        "requirements": ["Swift", "UIKit", "SwiftUI", "Core Data", "CI/CD"],
        "salary_min": 135000,
        "salary_max": 195000,
        "salary_currency": "USD",
        "apply_url": "https://spotify.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "5000+",
    },
    {
        "title": "Data Scientist",
        "company": "Netflix",
        "location": "Los Gatos, CA",
        "description": "Use machine learning and statistical modeling to optimize content recommendations and improve user engagement across Netflix's global audience.",
        "requirements": ["Python", "Machine Learning", "SQL", "A/B Testing", "TensorFlow"],
        "salary_min": 160000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "apply_url": "https://netflix.com/jobs",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "10000+",
    },
    {
        "title": "Product Designer",
        "company": "Figma",
        "location": "San Francisco, CA",
        "description": "Design tools that empower designers worldwide. Work on core product experiences, from collaborative editing to plugin ecosystem.",
        "requirements": ["Figma", "UX Research", "Prototyping", "Design Systems"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://figma.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "DevOps Engineer",
        "company": "GitHub",
        "location": "Remote",
        "description": "Build and maintain the infrastructure that powers GitHub's CI/CD platform. Work with Kubernetes, Terraform, and cloud-native technologies.",
        "requirements": ["Kubernetes", "Terraform", "AWS", "Docker", "CI/CD"],
        "salary_min": 130000,
        "salary_max": 185000,
        "salary_currency": "USD",
        "apply_url": "https://github.com/about/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "3000+",
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Anthropic",
        "location": "San Francisco, CA",
        "description": "Train and deploy large language models. Work on alignment research, model evaluation, and production infrastructure for AI safety.",
        "requirements": ["Python", "PyTorch", "LLMs", "CUDA", "Research"],
        "salary_min": 200000,
        "salary_max": 350000,
        "salary_currency": "USD",
        "apply_url": "https://anthropic.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "500+",
    },
    {
        "title": "Junior Software Engineer",
        "company": "Shopify",
        "location": "Remote",
        "description": "Join Shopify's engineering team and help build the commerce platform that powers millions of businesses worldwide. Mentorship and growth opportunities available.",
        "requirements": ["Ruby", "React", "SQL", "Git"],
        "salary_min": 90000,
        "salary_max": 130000,
        "salary_currency": "USD",
        "apply_url": "https://shopify.com/careers",
        "job_type": "Remote",
        "experience_level": "Junior",
        "company_logo_url": "",
        "company_size": "10000+",
    },
    {
        "title": "Engineering Manager",
        "company": "Discord",
        "location": "San Francisco, CA",
        "description": "Lead a team of backend engineers building Discord's real-time communication platform. Drive technical strategy and team growth.",
        "requirements": ["Management", "Distributed Systems", "Java", "System Design"],
        "salary_min": 180000,
        "salary_max": 260000,
        "salary_currency": "USD",
        "apply_url": "https://discord.com/jobs",
        "job_type": "On-site",
        "experience_level": "Lead",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "Frontend Developer — React",
        "company": "Vercel",
        "location": "Remote",
        "description": "Build the frontend of Vercel's deployment platform. Work on Next.js integration, dashboard UX, and developer tooling.",
        "requirements": ["React", "Next.js", "TypeScript", "Tailwind CSS"],
        "salary_min": 130000,
        "salary_max": 180000,
        "salary_currency": "USD",
        "apply_url": "https://vercel.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "200+",
    },
    {
        "title": "Platform Engineer",
        "company": "Datadog",
        "location": "New York, NY",
        "description": "Build the observability platform that engineers rely on. Work on distributed tracing, metrics ingestion, and real-time monitoring infrastructure.",
        "requirements": ["Go", "Kubernetes", "Distributed Systems", "Prometheus"],
        "salary_min": 145000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "apply_url": "https://datadog.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "4000+",
    },
    {
        "title": "Android Developer",
        "company": "Threads (Meta)",
        "location": "Menlo Park, CA",
        "description": "Build and enhance the Threads Android app. Work on social features, performance optimization, and the growing fediverse integration.",
        "requirements": ["Kotlin", "Jetpack Compose", "RxJava", "Android SDK"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://meta.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "50000+",
    },
    {
        "title": "QA Engineer",
        "company": "Cypress",
        "location": "Remote",
        "description": "Build testing tools that developers love. Work on the Cypress test runner, dashboard, and cloud services for end-to-end testing.",
        "requirements": ["JavaScript", "Cypress", "Playwright", "Testing"],
        "salary_min": 110000,
        "salary_max": 160000,
        "salary_currency": "USD",
        "apply_url": "https://cypress.io/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "200+",
    },
    {
        "title": "Technical Writer",
        "company": "ReadMe",
        "location": "Remote",
        "description": "Create developer documentation for APIs and SDKs. Work with engineering teams to produce clear, accurate, and helpful technical content.",
        "requirements": ["Technical Writing", "Markdown", "API Documentation", "Git"],
        "salary_min": 90000,
        "salary_max": 130000,
        "salary_currency": "USD",
        "apply_url": "https://readme.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "100+",
    },
    {
        "title": "Site Reliability Engineer",
        "company": "Google",
        "location": "Seattle, WA",
        "description": "Keep Google's services running reliably at planetary scale. Design and build automation, monitoring, and incident response systems.",
        "requirements": ["Python", "Go", "Kubernetes", "Linux", "Monitoring"],
        "salary_min": 160000,
        "salary_max": 240000,
        "salary_currency": "USD",
        "apply_url": "https://google.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "Software Engineer Intern",
        "company": "Microsoft",
        "location": "Redmond, WA",
        "description": "Summer internship program for students. Work on real products alongside experienced engineers. Open to CS/CE majors graduating in 2026 or 2027.",
        "requirements": ["Python", "C#", "Problem Solving", "Communication"],
        "salary_min": 6000,
        "salary_max": 9000,
        "salary_currency": "USD",
        "apply_url": "https://microsoft.com/university",
        "job_type": "On-site",
        "experience_level": "Internship",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "Security Engineer",
        "company": "CrowdStrike",
        "location": "Remote",
        "description": "Protect organizations from cyber threats using AI-powered detection. Work on endpoint security, threat intelligence, and incident response.",
        "requirements": ["Security", "Python", "Threat Analysis", "Cloud Security"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://crowdstrike.com/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "5000+",
    },
    {
        "title": "Product Manager",
        "company": "Linear",
        "location": "Remote",
        "description": "Define and ship features for Linear's issue tracking platform. Work closely with design and engineering to build tools that teams love.",
        "requirements": ["Product Strategy", "Analytics", "Technical Background", "UX"],
        "salary_min": 140000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://linear.app/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "50+",
    },
    {
        "title": "Blockchain Developer",
        "company": "Chainlink Labs",
        "location": "Remote",
        "description": "Build decentralized oracle networks that power smart contracts. Work on Solidity, Chainlink nodes, and cross-chain interoperability protocols.",
        "requirements": ["Solidity", "Ethereum", "Go", "Cryptography"],
        "salary_min": 150000,
        "salary_max": 250000,
        "salary_currency": "USD",
        "apply_url": "https://chainlinklabs.com/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "500+",
    },
    {
        "title": "Data Engineer",
        "company": "Snowflake",
        "location": "San Mateo, CA",
        "description": "Build data pipelines and infrastructure for Snowflake's cloud data platform. Work on ingestion, transformation, and query optimization at petabyte scale.",
        "requirements": ["Python", "SQL", "Spark", "Airflow", "Cloud"],
        "salary_min": 145000,
        "salary_max": 210000,
        "salary_currency": "USD",
        "apply_url": "https://snowflake.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "4000+",
    },
    {
        "title": "UX Researcher",
        "company": "Airbnb",
        "location": "San Francisco, CA",
        "description": "Conduct user research to inform product decisions across Airbnb's platform. Use qualitative and quantitative methods to uncover user needs.",
        "requirements": ["UX Research", "Qualitative Methods", "Data Analysis", "Presentation"],
        "salary_min": 120000,
        "salary_max": 170000,
        "salary_currency": "USD",
        "apply_url": "https://airbnb.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "5000+",
    },
    {
        "title": "Solutions Architect",
        "company": "AWS",
        "location": "New York, NY",
        "description": "Help enterprise customers design and implement cloud solutions on AWS. Work with C-level executives and engineering teams to drive cloud adoption.",
        "requirements": ["AWS", "Cloud Architecture", "Communication", "Enterprise"],
        "salary_min": 150000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "apply_url": "https://aws.amazon.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "50000+",
    },
    {
        "title": "React Native Developer",
        "company": "Coinbase",
        "location": "Remote",
        "description": "Build Coinbase's mobile trading experience using React Native. Work on real-time market data, portfolio management, and crypto transactions.",
        "requirements": ["React Native", "TypeScript", "Mobile", "Crypto"],
        "salary_min": 135000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://coinbase.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "3000+",
    },
    {
        "title": "AI Research Scientist",
        "company": "OpenAI",
        "location": "San Francisco, CA",
        "description": "Conduct cutting-edge research in artificial intelligence. Work on multimodal models, reasoning, safety, and alignment with world-class researchers.",
        "requirements": ["PhD", "PyTorch", "Deep Learning", "NLP", "Research Publications"],
        "salary_min": 250000,
        "salary_max": 400000,
        "salary_currency": "USD",
        "apply_url": "https://openai.com/careers",
        "job_type": "On-site",
        "experience_level": "Lead",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "Customer Success Engineer",
        "company": "Supabase",
        "location": "Remote",
        "description": "Help developers succeed with Supabase's open-source backend platform. Provide technical support, create documentation, and gather product feedback.",
        "requirements": ["PostgreSQL", "JavaScript", "Customer Facing", "Documentation"],
        "salary_min": 100000,
        "salary_max": 145000,
        "salary_currency": "USD",
        "apply_url": "https://supabase.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "100+",
    },
    {
        "title": "Database Reliability Engineer",
        "company": "PlanetScale",
        "location": "Remote",
        "description": "Operate and improve PlanetScale's MySQL-compatible serverless database platform. Work on replication, backups, and query performance.",
        "requirements": ["MySQL", "Vitess", "Go", "SRE", "Performance"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://planetscale.com/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "100+",
    },
    {
        "title": "Growth Engineer",
        "company": "Linear",
        "location": "Remote",
        "description": "Drive user growth through experiments, onboarding improvements, and data-driven feature development. Full-stack role with product impact.",
        "requirements": ["React", "Node.js", "A/B Testing", "Analytics", "Growth"],
        "salary_min": 130000,
        "salary_max": 180000,
        "salary_currency": "USD",
        "apply_url": "https://linear.app/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "50+",
    },
    {
        "title": "Systems Software Engineer",
        "company": "Apple",
        "location": "Cupertino, CA",
        "description": "Work on macOS/iOS system software. Develop kernel extensions, device drivers, and performance optimization for Apple's hardware ecosystem.",
        "requirements": ["C", "C++", "Operating Systems", "Kernel", "ARM"],
        "salary_min": 150000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "apply_url": "https://apple.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "Developer Advocate",
        "company": "Supabase",
        "location": "Remote",
        "description": "Be the voice of Supabase in the developer community. Create content, speak at events, build demos, and foster open-source community growth.",
        "requirements": ["Public Speaking", "Content Creation", "JavaScript", "Community"],
        "salary_min": 110000,
        "salary_max": 155000,
        "salary_currency": "USD",
        "apply_url": "https://supabase.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "100+",
    },
    {
        "title": "Compliance Engineer",
        "company": "Plaid",
        "location": "San Francisco, CA",
        "description": "Build and maintain compliance and security infrastructure for Plaid's financial data platform. Ensure SOC2, PCI, and GDPR compliance.",
        "requirements": ["Security", "Compliance", "Python", "Infrastructure", "Audit"],
        "salary_min": 130000,
        "salary_max": 180000,
        "salary_currency": "USD",
        "apply_url": "https://plaid.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "Embedded Systems Engineer",
        "company": "Tesla",
        "location": "Palo Alto, CA",
        "description": "Develop embedded software for Tesla vehicles. Work on real-time control systems, firmware updates, and vehicle telemetry.",
        "requirements": ["C", "C++", "RTOS", "Embedded Linux", "CAN Bus"],
        "salary_min": 130000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://tesla.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "API Engineer",
        "company": "Twilio",
        "location": "Remote",
        "description": "Design and build Twilio's communication APIs. Focus on developer experience, performance, and reliability of customer engagement APIs.",
        "requirements": ["REST", "API Design", "Python", "Documentation", "Testing"],
        "salary_min": 130000,
        "salary_max": 185000,
        "salary_currency": "USD",
        "apply_url": "https://twilio.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "5000+",
    },
    {
        "title": "Frontend Engineer — Design Systems",
        "company": "Adobe",
        "location": "San Jose, CA",
        "description": "Build and maintain Adobe's Spectrum design system. Create reusable components, documentation, and tooling used across all Adobe products.",
        "requirements": ["React", "TypeScript", "Design Systems", "Storybook", "CSS"],
        "salary_min": 130000,
        "salary_max": 185000,
        "salary_currency": "USD",
        "apply_url": "https://adobe.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "20000+",
    },
    {
        "title": "Network Engineer",
        "company": "Cloudflare",
        "location": "London, UK",
        "description": "Design and operate Cloudflare's global network. Work on backbone infrastructure, DDoS mitigation, and edge networking technologies.",
        "requirements": ["Networking", "BGP", "Linux", "Automation", "DDoS"],
        "salary_min": 120000,
        "salary_max": 175000,
        "salary_currency": "USD",
        "apply_url": "https://cloudflare.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "3000+",
    },
    {
        "title": "Junior Data Analyst",
        "company": "HubSpot",
        "location": "Cambridge, MA",
        "description": "Support data-driven decision making across HubSpot. Build dashboards, run analyses, and present insights to stakeholders. Great growth opportunity.",
        "requirements": ["SQL", "Excel", "Python", "Tableau", "Communication"],
        "salary_min": 65000,
        "salary_max": 85000,
        "salary_currency": "USD",
        "apply_url": "https://hubspot.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Junior",
        "company_logo_url": "",
        "company_size": "7000+",
    },
    {
        "title": "Compilers Engineer",
        "company": "JetBrains",
        "location": "Remote",
        "description": "Work on IntelliJ and Kotlin compiler tooling. Develop language features, code analysis, and IDE integrations for millions of developers.",
        "requirements": ["Kotlin", "Java", "Compiler Design", "JVM"],
        "salary_min": 130000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://jetbrains.com/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "Gameplay Engineer",
        "company": "Riot Games",
        "location": "Los Angeles, CA",
        "description": "Build gameplay systems for League of Legends. Work on champion abilities, game mechanics, and real-time multiplayer systems.",
        "requirements": ["C++", "Unreal Engine", "Game Design", "Networking"],
        "salary_min": 120000,
        "salary_max": 180000,
        "salary_currency": "USD",
        "apply_url": "https://riotgames.com/careers",
        "job_type": "On-site",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "4000+",
    },
    {
        "title": "AR/VR Engineer",
        "company": "Meta (Reality Labs)",
        "location": "Redmond, WA",
        "description": "Build augmented reality experiences for Meta's Quest platform. Work on spatial computing, hand tracking, and mixed reality applications.",
        "requirements": ["C++", "Unity", "Computer Vision", "3D Graphics"],
        "salary_min": 150000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "apply_url": "https://meta.com/careers",
        "job_type": "On-site",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "50000+",
    },
    {
        "title": "GraphQL API Developer",
        "company": "Apollo GraphQL",
        "location": "Remote",
        "description": "Build and maintain Apollo's GraphQL federation platform. Work on gateway, schema management, and developer tooling for distributed graphs.",
        "requirements": ["GraphQL", "TypeScript", "Node.js", "Apollo Federation"],
        "salary_min": 130000,
        "salary_max": 185000,
        "salary_currency": "USD",
        "apply_url": "https://apollographql.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "200+",
    },
    {
        "title": "Technical Program Manager",
        "company": "Databricks",
        "location": "San Francisco, CA",
        "description": "Drive cross-functional programs across Databricks' data and AI platform. Coordinate engineering, product, and go-to-market teams.",
        "requirements": ["Program Management", "Technical Background", "Data", "AI"],
        "salary_min": 140000,
        "salary_max": 200000,
        "salary_currency": "USD",
        "apply_url": "https://databricks.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "4000+",
    },
    {
        "title": "Frontend Developer — Vue.js",
        "company": "Nuxt Labs",
        "location": "Remote",
        "description": "Build features for Nuxt's web framework ecosystem. Work on the Vue.js framework, dev tools, and documentation for the open-source community.",
        "requirements": ["Vue.js", "TypeScript", "Nuxt", "Node.js", "Open Source"],
        "salary_min": 110000,
        "salary_max": 160000,
        "salary_currency": "USD",
        "apply_url": "https://nuxt.com/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "50+",
    },
    {
        "title": "Sales Engineer",
        "company": "Datadog",
        "location": "New York, NY",
        "description": "Support the sales team with technical expertise. Deliver demos, run proof-of-concepts, and help customers understand Datadog's monitoring platform.",
        "requirements": ["Cloud", "Monitoring", "Presentation", "DevOps", "Python"],
        "salary_min": 120000,
        "salary_max": 170000,
        "salary_currency": "USD",
        "apply_url": "https://datadog.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "4000+",
    },
    {
        "title": "Principal Software Architect",
        "company": "Microsoft",
        "location": "Redmond, WA",
        "description": "Define technical architecture for Azure services. Drive standards, review designs, and mentor engineering teams across multiple product groups.",
        "requirements": ["System Design", "Cloud", "Leadership", "Distributed Systems"],
        "salary_min": 220000,
        "salary_max": 320000,
        "salary_currency": "USD",
        "apply_url": "https://microsoft.com/careers",
        "job_type": "On-site",
        "experience_level": "Principal",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "Penetration Tester",
        "company": "HackerOne",
        "location": "Remote",
        "description": "Conduct security assessments and penetration tests for enterprise customers. Identify vulnerabilities and help organizations improve their security posture.",
        "requirements": ["Penetration Testing", "Web Security", "Python", "Reporting"],
        "salary_min": 120000,
        "salary_max": 180000,
        "salary_currency": "USD",
        "apply_url": "https://hackerone.com/careers",
        "job_type": "Remote",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "500+",
    },
    {
        "title": "Rust Systems Developer",
        "company": "Figma",
        "location": "San Francisco, CA",
        "description": "Rewrite Figma's rendering engine in Rust for performance. Work on WebGL, canvas rendering, and cross-platform graphics pipelines.",
        "requirements": ["Rust", "WebAssembly", "Graphics", "Performance", "C++"],
        "salary_min": 150000,
        "salary_max": 220000,
        "salary_currency": "USD",
        "apply_url": "https://figma.com/careers",
        "job_type": "Hybrid",
        "experience_level": "Senior",
        "company_logo_url": "",
        "company_size": "1000+",
    },
    {
        "title": "Accessibility Engineer",
        "company": "Apple",
        "location": "Cupertino, CA",
        "description": "Ensure Apple's products are accessible to all users. Work on VoiceOver, Dynamic Text, Switch Control, and other assistive technologies.",
        "requirements": ["Accessibility", "iOS/macOS", "VoiceOver", "WCAG", "Empathy"],
        "salary_min": 130000,
        "salary_max": 190000,
        "salary_currency": "USD",
        "apply_url": "https://apple.com/careers",
        "job_type": "On-site",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "100000+",
    },
    {
        "title": "Cloud Cost Engineer",
        "company": "Snyk",
        "location": "Remote",
        "description": "Help Snyk customers optimize cloud infrastructure costs. Build tooling for cloud cost analysis, resource right-sizing, and budget management.",
        "requirements": ["AWS", "GCP", "Terraform", "Python", "FinOps"],
        "salary_min": 120000,
        "salary_max": 170000,
        "salary_currency": "USD",
        "apply_url": "https://snyk.io/careers",
        "job_type": "Remote",
        "experience_level": "Mid-Senior",
        "company_logo_url": "",
        "company_size": "500+",
    },
    {
        "title": "Developer Relations Engineer",
        "company": "Neon",
        "location": "Remote",
        "description": "Build and nurture the developer community for Neon's serverless Postgres platform. Create content, respond to feedback, and advocate for developers.",
        "requirements": ["PostgreSQL", "Content Creation", "Community", "JavaScript"],
        "salary_min": 110000,
        "salary_max": 155000,
        "salary_currency": "USD",
        "apply_url": "https://neon.tech/careers",
        "job_type": "Remote",
        "experience_level": "Mid",
        "company_logo_url": "",
        "company_size": "100+",
    },
]


def get_mock_jobs():
    now = datetime.now(timezone.utc)
    jobs = []
    for i, data in enumerate(MOCK_JOBS):
        job = dict(data)
        job["posted_at"] = now - timedelta(days=i % 30, hours=i)
        job["source"] = "mock"
        jobs.append(job)
    return jobs
